### ISSUE TITLE
pip 10.x install breaks on unused parse_requirements import in setup.py

### ISSUE THREAD

**Issue by elwinarens** [pmuller/django-crowd-auth#10]
*pip 10.X+* has moved the module `pip.req` to `pip._internal.req`, which causes `setup.py` to fail for *pip 10.X+* on this include:

    from pip.req import parse_requirements

Causes the following error:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File ".../django-crowd-auth/setup.py", line 4, in <module>
        from pip.req import parse_requirements
    ImportError: No module named 'pip.req'

https://github.com/pmuller/django-crowd-auth/blob/master/setup.py#L4

Additionally, the `parse_requirements` function is not used as far as i can tell, so it seems this entire import can be removed.

**Comment by pmuller** [comment]
Well spotted, thanks! I merged your PR.

**Comment by elwinarens** [comment]
Thanks for the merge! Would you mind creating a new release that ends up in pip? So i can remove the pip github requirement.
